---

- name: activate ipv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1 state=present reload=yes

- name: deactivate ipv4 rp filter
  sysctl: name=net.ipv4.conf.all.rp_filter value=0 state=present reload=yes

- name: deactivate ipv4 default rp filter
  sysctl: name=net.ipv4.conf.default.rp_filter value=0 state=present reload=yes


- name: setting sysctl
  template: src=sysctl.conf dest=/etc/sysctl.conf backup=yes
  notify:
    - implement the sysctl

- name: install compute-related neutron packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - neutron-plugin-ml2
    - neutron-plugin-openvswitch-agent

- name: config neutron
  template: src=neutron.conf dest=/etc/neutron/neutron.conf backup=yes
  notify:
    - restart neutron-plugin-openvswitch-agent

- name: config ml2 plugin
  template: src=ml2_conf.ini dest=/etc/neutron/plugins/ml2/ml2_conf.ini backup=yes
  notify:
    - restart neutron-plugin-openvswitch-agent 
    - restart nova-compute

- meta: flush_handlers
