---
- name: install nova-compute related packages
  apt: name={{ item }} state=present force=yes
  with_items:
    - nova-compute
    - sysfsutils

- name: update nova-compute conf
  template: src={{ item }} dest=/etc/nova/{{ item }} backup=yes
  with_items:
    - nova.conf
  notify:
    - restart nova-compute

- meta: flush_handlers

- name: remove nova sqlite db
  shell: rm /var/lib/nova/nova.sqlite || touch nova.sqlite.removed
